### ISSUE TITLE
Use yard for generated documentation

### ISSUE THREAD

**Issue by kobliha** [yast/yast-services-manager#7]
- For instance, modules have public API, it makes sense to have their docs generated

**Comment by cwh42** [comment]
Some methods have yard doc, in the meantime. We just need to generate it and store it somewhere.

**Comment by jreidinger** [comment]
it is done by third party at https://rubydoc.info/github/yast/yast-services-manager/master
we just need to add link to README like other YaST module doing it.

**Comment by ancorgs** [comment]
The status in that regard is not different to other YaST modules. We already have cards to improve all READMEs anyway.

So closing.
